### PR TITLE
Maven Docker Build improvements

### PR DESCRIPTION
**Pull request by oalagtash**
Included changes:

- One mvn deploy command to deploy all docker images in the repository.
- Unified and simplified `docker-maven-plugin` configuration.
- Allow having different namespace and username. 
- Added missing docker healthcheck.
- Changed wrong java version of registry-aas from 11 to 17.

### CODE REVIEW

**Comment by FrankSchnicke** [comment]
Thanks a lot for your contribution! However, the Eclipse Contributer Agreement check is failing. Did you link your GitHub account with your Eclipse account? Are you using the same mails?

**Comment by oalagtash** [comment]
The build is failing on aas registry - probably because I increased the java version to from 11 to 17. 
The image being used is java-17. I would suggest we either downgrade the docker image to java-11 or try fixing this error. 
I also noticed that submodel registry is already on java-17.

**Comment by FrankSchnicke** [comment]
Since Spring 3 is using Java 17 would a downgrade really help?

**Comment by oalagtash** [comment]
> Since Spring 3 is using Java 17 would a downgrade really help?

It makes probably more sense to fix the errors instead of downgrading.

**Review by mdanish98 — APPROVED** [review]
Approved.

**Pull request merged**
