### PR TITLE
Add healthcheck in components dockerfile

### PR DESCRIPTION
**Pull request by mhrimaz**
With the integrated healthcheck, it is easier to determine container health.

image

As further addition it would be nice to bump the jdk base image to eclipse temurin jdk 17.

What do you think? @FrankSchnicke

### CODE REVIEW

**Comment by FrankSchnicke** [comment]
Integrating the healthcheck directly in the container is a good idea. However, polling the /shells etc. endpoint might create a high load on backend etc. Can you update the PR to use the explicit [health endpoint](https://github.com/eclipse-basyx/basyx-java-server-sdk/blob/main/docs/Readme.md#health-endpoint)?

**Comment by mhrimaz** [comment]
> Integrating the healthcheck directly in the container is a good idea. However, polling the /shells etc. endpoint might create a high load on backend etc. Can you update the PR to use the explicit [health endpoint](https://github.com/eclipse-basyx/basyx-java-server-sdk/blob/main/docs/Readme.md#health-endpoint)?

I will do that, but before that, I need to know if management path should be configurable or not.

The latest aas environment docker `digest: 3471dea2cf82` does not have `/health` endpoint. It is reachable via `/actuator/health`. This is because of commenting out the following config:
```
# Base Path for Spring Boot Actuator
management.endpoints.web.base-path=/
```
So it seems `/health` can change and if someone changes that (accidentally/intentionally), then the whole logic would break. So I need to find a more dynamic way if this case is intended.

**Comment by FrankSchnicke** [comment]
Thanks for pointing this out, we missed updating the documentation for this. I'm currently not aware of a use case where reconfiguring the health endpoint's location would make sense in our contexts. Thus, you can assume it to always be at _/actuator/health_

**Comment by FrankSchnicke** [comment]
Hi @mhrimaz, any update on this? Is this still of relevance for you?

**Comment by mhrimaz** [comment]
@FrankSchnicke should be fine now. Also check #138 if you need base image bump.

**Comment by FrankSchnicke** [comment]
Thanks a lot for this PR. If you mark it as "ready for review", I will merge it.

**Pull request merged**
